--前置条件
sql:dbscale set global "use-partial-parse" = 1;
--alter table ，text字段，collate从utf8mb4_bin到utf8mb4_general_ci 3551
sql:create database test1;
sql:use test1;
sql:create table test1.tb_alter (id int primary key auto_increment,c1 text character set utf8mb4  collate utf8mb4_bin);
sql:insert into test1.tb_alter (c1) values ("A");
sql:insert into test1.tb_alter (c1) values ("B");
sql:insert into test1.tb_alter (c1) values ("C");
sql:insert into test1.tb_alter (c1) values ("D");
sql:insert into test1.tb_alter (c1) values ("E");
sql:insert into test1.tb_alter (c1) values ("F");
sql:insert into test1.tb_alter (c1) values ("G");
sql:insert into test1.tb_alter (c1) values ("B");
sql:insert into test1.tb_alter (c1) values ("C");
sql:insert into test1.tb_alter (c1) values ("D");
sql:insert into test1.tb_alter (c1) values ("E");
sql:insert into test1.tb_alter (c1) values ("H");
sql:insert into test1.tb_alter (c1) values ("B");
sql:insert into test1.tb_alter (c1) values ("C");
sql:insert into test1.tb_alter (c1) values ("D");
sql:insert into test1.tb_alter (c1) values ("E");
sql:insert into test1.tb_alter (c1) values ("F");
sql:insert into test1.tb_alter (c1) values ("G");
sql:insert into test1.tb_alter (c1) values ("H");
sql:insert into test1.tb_alter (c1) values ("B");
sql:insert into test1.tb_alter (c1) values ("C");
sql:insert into test1.tb_alter (c1) values ("D");
sql:select distinct c1 from  test1.tb_alter;
sql:select id,c1 from  test1.tb_alter order by c1;
sql:select c1 from  test1.tb_alter group by c1;
sql:select id,c1 from  test1.tb_alter having id < 8;
sql:select id,c1 from  test1.tb_alter where id > 5;
sql:select TABLE_NAME,COLLATION_NAME,DATA_TYPE from information_schema.columns where table_schema = "test1" and table_name = "test1.tb_alter";
sql:alter table  test1.tb_alter change column c1 ca  text character set utf8mb4 collate utf8mb4_general_ci;
sql:select TABLE_NAME,COLLATION_NAME,DATA_TYPE from information_schema.columns where table_schema = "test1" and table_name = "test1.tb_alter";
sql:drop database test1;

--procedure ，输入参数char字段，编码gbk，collate使用gbk_bin 	3553
sql:create database test1;
sql:use test1;
sql:create table test1.tb_char_gbk_bin (id int primary key auto_increment,c1 char(12) character set gbk  collate gbk_bin);
sql:insert into test1.tb_char_gbk_bin (c1) values ("一");
sql:insert into test1.tb_char_gbk_bin (c1) values ("二");
sql:insert into test1.tb_char_gbk_bin (c1) values ("三");
sql:insert into test1.tb_char_gbk_bin (c1) values ("四");
sql:insert into test1.tb_char_gbk_bin (c1) values ("五");
sql:insert into test1.tb_char_gbk_bin (c1) values ("六");
sql:insert into test1.tb_char_gbk_bin (c1) values ("七");
sql:insert into test1.tb_char_gbk_bin (c1) values ("二");
sql:insert into test1.tb_char_gbk_bin (c1) values ("三");
sql:insert into test1.tb_char_gbk_bin (c1) values ("四");
sql:insert into test1.tb_char_gbk_bin (c1) values ("五");
sql:insert into test1.tb_char_gbk_bin (c1) values ("八");
sql:insert into test1.tb_char_gbk_bin (c1) values ("二");
sql:insert into test1.tb_char_gbk_bin (c1) values ("三");
sql:insert into test1.tb_char_gbk_bin (c1) values ("四");
sql:insert into test1.tb_char_gbk_bin (c1) values ("五");
sql:insert into test1.tb_char_gbk_bin (c1) values ("六");
sql:insert into test1.tb_char_gbk_bin (c1) values ("七");
sql:insert into test1.tb_char_gbk_bin (c1) values ("八");
sql:insert into test1.tb_char_gbk_bin (c1) values ("二");
sql:insert into test1.tb_char_gbk_bin (c1) values ("三");
sql:insert into test1.tb_char_gbk_bin (c1) values ("四");
--DELIMITER // 
--CREATE PROCEDURE test1.test_procedure (IN p_in char(12) character set gbk  collate gbk_bin) BEGIN select distinct c1 from  test1.tb_char_gbk_bin; select id,c1 from  test1.tb_char_gbk_bin order by c1; select c1 from   test1.tb_char_gbk_bin group by c1; select id,c1 from  test1.tb_char_gbk_bin having id < 8; select id,c1 from  test1.tb_char_gbk_bin where id > 5;END //
--DELIMITER ;
--call test1.test_procedure("a");
--show CREATE PROCEDURE test1.test_procedure\G;
--drop procedure test1.test_procedure;
sql:drop database test1;
