--前置条件
sql:dbscale set global "use-partial-parse" = 1;

--alter table ，char字段，collate从utf8mb4_bin到utf8mb4_general_ci 3549 
sql:create database test1;
sql:use test1;
sql:create table test1.tb_alter (id int primary key auto_increment,c1 char(12) character set utf8mb4  collate utf8mb4_bin);
sql:insert into test1.tb_alter (c1) values ("A");
sql:insert into test1.tb_alter (c1) values ("B");
sql:insert into test1.tb_alter (c1) values ("C");
sql:insert into test1.tb_alter (c1) values ("D");
sql:insert into test1.tb_alter (c1) values ("E");
sql:insert into test1.tb_alter (c1) values ("F");
sql:insert into test1.tb_alter (c1) values ("G");
sql:insert into test1.tb_alter (c1) values ("B");
sql:insert into test1.tb_alter (c1) values ("C");
sql:insert into test1.tb_alter (c1) values ("D");
sql:insert into test1.tb_alter (c1) values ("E");
sql:insert into test1.tb_alter (c1) values ("F");
sql:insert into test1.tb_alter (c1) values ("B");
sql:insert into test1.tb_alter (c1) values ("C");
sql:insert into test1.tb_alter (c1) values ("D");
sql:insert into test1.tb_alter (c1) values ("E");
sql:insert into test1.tb_alter (c1) values ("F");
sql:insert into test1.tb_alter (c1) values ("G");
sql:insert into test1.tb_alter (c1) values ("H");
sql:insert into test1.tb_alter (c1) values ("B");
sql:insert into test1.tb_alter (c1) values ("C");
sql:insert into test1.tb_alter (c1) values ("D");
sql:select distinct c1 from  test1.tb_alter;
sql:select id,c1 from  test1.tb_alter order by c1;
sql:select c1 from  test1.tb_alter group by c1;
sql:select id,c1 from  test1.tb_alter having id < 8;
sql:select id,c1 from  test1.tb_alter where id > 5;
sql:select TABLE_NAME,COLLATION_NAME,DATA_TYPE from information_schema.columns where table_schema = "test1" and table_name = "test1.tb_alter";
sql:alter table  test1.tb_alter change column c1 ca  char(6) character set utf8mb4 collate utf8mb4_general_ci;
sql:select TABLE_NAME,COLLATION_NAME,DATA_TYPE from information_schema.columns where table_schema = "test1" and table_name = "test1.tb_alter";
sql:drop database test1;	

--alter table ，varchar字段，collate从utf8mb4_bin到utf8mb4_general_ci 3550
sql:create database test1;
sql:use test1;
sql:create table test1.tb_alter (id int primary key auto_increment,c1 varchar(12) character set utf8mb4  collate utf8mb4_bin);
sql:insert into test1.tb_alter (c1) values ("A");
sql:insert into test1.tb_alter (c1) values ("B");
sql:insert into test1.tb_alter (c1) values ("C");
sql:insert into test1.tb_alter (c1) values ("D");
sql:insert into test1.tb_alter (c1) values ("E");
sql:insert into test1.tb_alter (c1) values ("F");
sql:insert into test1.tb_alter (c1) values ("G");
sql:insert into test1.tb_alter (c1) values ("B");
sql:insert into test1.tb_alter (c1) values ("C");
sql:insert into test1.tb_alter (c1) values ("D");
sql:insert into test1.tb_alter (c1) values ("E");
sql:insert into test1.tb_alter (c1) values ("F");
sql:insert into test1.tb_alter (c1) values ("B");
sql:insert into test1.tb_alter (c1) values ("C");
sql:insert into test1.tb_alter (c1) values ("D");
sql:insert into test1.tb_alter (c1) values ("E");
sql:insert into test1.tb_alter (c1) values ("F");
sql:insert into test1.tb_alter (c1) values ("G");
sql:insert into test1.tb_alter (c1) values ("H");
sql:insert into test1.tb_alter (c1) values ("B");
sql:insert into test1.tb_alter (c1) values ("C");
sql:insert into test1.tb_alter (c1) values ("D");
sql:select distinct c1 from  test1.tb_alter;
sql:select id,c1 from  test1.tb_alter order by c1;
sql:select c1 from  test1.tb_alter group by c1;
sql:select id,c1 from  test1.tb_alter having id < 8;
sql:select id,c1 from  test1.tb_alter where id > 5;		
sql:select TABLE_NAME,COLLATION_NAME,DATA_TYPE from information_schema.columns where table_schema = "test1" and table_name = "test1.tb_alter";
sql:alter table  test1.tb_alter change column c1 ca  varchar(6) character set utf8mb4 collate utf8mb4_general_ci;
sql:select TABLE_NAME,COLLATION_NAME,DATA_TYPE from information_schema.columns where table_schema = "test1" and table_name = "test1.tb_alter";
sql:drop database test1;