--前置条件
sql:dbscale set global "use-partial-parse" = 1; 
--alter table ，char字段，collate从gbk_bin到gbk_chinese_ci 3546
sql:create database test1;
sql:use test1;
sql:create table test1.tb_alter (id int primary key auto_increment,c1 char(12) character set gbk  collate gbk_bin);
sql:insert into test1.tb_alter (c1) values ("一");
sql:insert into test1.tb_alter (c1) values ("二");
sql:insert into test1.tb_alter (c1) values ("三");
sql:insert into test1.tb_alter (c1) values ("四");
sql:insert into test1.tb_alter (c1) values ("五");
sql:insert into test1.tb_alter (c1) values ("六");
sql:insert into test1.tb_alter (c1) values ("七");
sql:insert into test1.tb_alter (c1) values ("二");
sql:insert into test1.tb_alter (c1) values ("三");
sql:insert into test1.tb_alter (c1) values ("四");
sql:insert into test1.tb_alter (c1) values ("五");
sql:insert into test1.tb_alter (c1) values ("八");
sql:insert into test1.tb_alter (c1) values ("二");
sql:insert into test1.tb_alter (c1) values ("三");
sql:insert into test1.tb_alter (c1) values ("四");
sql:insert into test1.tb_alter (c1) values ("五");
sql:insert into test1.tb_alter (c1) values ("六");
sql:insert into test1.tb_alter (c1) values ("七");
sql:insert into test1.tb_alter (c1) values ("八");
sql:insert into test1.tb_alter (c1) values ("二");
sql:insert into test1.tb_alter (c1) values ("三");
sql:insert into test1.tb_alter (c1) values ("四");
sql:select distinct c1 from  test1.tb_alter;
sql:select id,c1 from  test1.tb_alter order by c1;
sql:select c1 from  test1.tb_alter group by c1;
sql:select id,c1 from  test1.tb_alter having id < 8;
sql:select id,c1 from  test1.tb_alter where id > 5;
sql:select TABLE_NAME,COLLATION_NAME,DATA_TYPE from information_schema.columns where table_schema = "test1" and table_name = "test1.tb_alter";
sql:alter table  test1.tb_alter change column c1 ca  char(6) character set gbk collate gbk_chinese_ci;
sql:select TABLE_NAME,COLLATION_NAME,DATA_TYPE from information_schema.columns where table_schema = "test1" and table_name = "test1.tb_alter";
sql:drop database test1;

--alter table ，varchar字段，collate从gbk_bin到gbk_chinese_ci 3547
sql:create database test1;
sql:use test1;
sql:create table test1.tb_alter (id int primary key auto_increment,c1 varchar(12) character set gbk  collate gbk_bin);
sql:insert into test1.tb_alter (c1) values ("一");
sql:insert into test1.tb_alter (c1) values ("二");
sql:insert into test1.tb_alter (c1) values ("三");
sql:insert into test1.tb_alter (c1) values ("四");
sql:insert into test1.tb_alter (c1) values ("五");
sql:insert into test1.tb_alter (c1) values ("六");
sql:insert into test1.tb_alter (c1) values ("七");
sql:insert into test1.tb_alter (c1) values ("二");
sql:insert into test1.tb_alter (c1) values ("三");
sql:insert into test1.tb_alter (c1) values ("四");
sql:insert into test1.tb_alter (c1) values ("五");
sql:insert into test1.tb_alter (c1) values ("八");
sql:insert into test1.tb_alter (c1) values ("二");
sql:insert into test1.tb_alter (c1) values ("三");
sql:insert into test1.tb_alter (c1) values ("四");
sql:insert into test1.tb_alter (c1) values ("五");
sql:insert into test1.tb_alter (c1) values ("六");
sql:insert into test1.tb_alter (c1) values ("七");
sql:insert into test1.tb_alter (c1) values ("八");
sql:insert into test1.tb_alter (c1) values ("二");
sql:insert into test1.tb_alter (c1) values ("三");
sql:insert into test1.tb_alter (c1) values ("四");
sql:select distinct c1 from  test1.tb_alter;
sql:select id,c1 from  test1.tb_alter order by c1;
sql:select c1 from  test1.tb_alter group by c1;
sql:select id,c1 from  test1.tb_alter having id < 8;
sql:select id,c1 from  test1.tb_alter where id > 5;
sql:select TABLE_NAME,COLLATION_NAME,DATA_TYPE from information_schema.columns where table_schema = "test1" and table_name = "test1.tb_alter";
sql:alter table  test1.tb_alter change column c1 ca  varchar(6) character set gbk collate gbk_chinese_ci;
sql:select TABLE_NAME,COLLATION_NAME,DATA_TYPE from information_schema.columns where table_schema = "test1" and table_name = "test1.tb_alter";
sql:drop database test1;

--alter table ，text字段，collate从gbk_bin到gbk_chinese_ci 3548
sql:create database test1;
sql:use test1;
sql:create table test1.tb_alter (id int primary key auto_increment,c1 text character set gbk  collate gbk_bin);
sql:insert into test1.tb_alter (c1) values ("一");
sql:insert into test1.tb_alter (c1) values ("二");
sql:insert into test1.tb_alter (c1) values ("三");
sql:insert into test1.tb_alter (c1) values ("四");
sql:insert into test1.tb_alter (c1) values ("五");
sql:insert into test1.tb_alter (c1) values ("六");
sql:insert into test1.tb_alter (c1) values ("七");
sql:insert into test1.tb_alter (c1) values ("二");
sql:insert into test1.tb_alter (c1) values ("三");
sql:insert into test1.tb_alter (c1) values ("四");
sql:insert into test1.tb_alter (c1) values ("五");
sql:insert into test1.tb_alter (c1) values ("八");
sql:insert into test1.tb_alter (c1) values ("二");
sql:insert into test1.tb_alter (c1) values ("三");
sql:insert into test1.tb_alter (c1) values ("四");
sql:insert into test1.tb_alter (c1) values ("五");
sql:insert into test1.tb_alter (c1) values ("六");
sql:insert into test1.tb_alter (c1) values ("七");
sql:insert into test1.tb_alter (c1) values ("八");
sql:insert into test1.tb_alter (c1) values ("二");
sql:insert into test1.tb_alter (c1) values ("三");
sql:insert into test1.tb_alter (c1) values ("四");
sql:select distinct c1 from  test1.tb_alter;
sql:select id,c1 from  test1.tb_alter order by c1;
sql:select c1 from  test1.tb_alter group by c1;
sql:select id,c1 from  test1.tb_alter having id < 8;
sql:select id,c1 from  test1.tb_alter where id > 5;	
sql:select TABLE_NAME,COLLATION_NAME,DATA_TYPE from information_schema.columns where table_schema = "test1" and table_name = "test1.tb_alter";
sql:alter table  test1.tb_alter change column c1 ca  text character set gbk collate gbk_chinese_ci;
sql:select TABLE_NAME,COLLATION_NAME,DATA_TYPE from information_schema.columns where table_schema = "test1" and table_name = "test1.tb_alter";
sql:drop database test1;
